################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.5"
services:
  nodered:
    build: node-red
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - node-red:/data
    env_file:
      - .env
  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"

volumes:
  node-red:

# networks:
#  node-red-net: