################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.5"
services:
  nodered:
    build: node-red
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
#    networks:
#      - node-red-net
    volumes:
      - node-red:/data
    env_file:
      - .env
  db:
    image: influxdb:latest
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdb:/var/lib/influxdb

volumes:
  node-red:
  influxdb:

# networks:
#  node-red-net: